i3-config: /home/j/.config/i3/config
polybar-config: /home/j/.config/polybar/config
xresources: /home/j/.Xresources
nitrogen-config: /home/j/.config/nitrogen/bg-saved.cfg
wallpaper-path: /home/j/.config/nitrogen/
